_target_: fusion_bench.modelpool.CausalLMPool

pretrained_model_name_or_path: mistralai/Mixtral-8x7B-v0.1

models:
  _pretrained_:
    _target_: transformers.AutoModelForCausalLM.from_pretrained
    pretrained_model_name_or_path: ${...pretrained_model_name_or_path}
    torch_dtype: bfloat16
    device_map: auto

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${..pretrained_model_name_or_path}
