_target_: fusion_bench.modelpool.CausalLMPool
_recursive_: false
models:
  _pretrained_: Qwen/Qwen2.5-7B
  math: Qwen/Qwen2.5-Math-7B
  code: Qwen/Qwen2.5-Coder-7B
model_kwargs:
  torch_dtype: bfloat16
tokenizer: Qwen/Qwen2.5-7B
