_target_: fusion_bench.modelpool.CausalLMPool
_recursive_: false
models:
  _pretrained_: meta-llama/Llama-2-7b-hf
  finetuned_model: lmsys/vicuna-7b-v1.5
model_kwargs:
  torch_dtype: bfloat16
tokenizer: ${.models.finetuned_model}
