_target_: fusion_bench.method.TaskSingularVectorMerging
exclude_keys: null
# alpha is a float or a list of floats
# example:
# alpha: 1
# alpha: [1, 0.5, 0.25]
alpha: 1
return_single_task_models: false
