_target_: fusion_bench.modelpool.CausalLMPool
_recursive_: false
models:
  _pretrained_:
    _target_: transformers.AutoModelForCausalLM.from_pretrained
    pretrained_model_name_or_path: mistralai/Mistral-7B-v0.1
  expert_1:
    _target_: transformers.AutoModelForCausalLM.from_pretrained
    pretrained_model_name_or_path: meta-math/MetaMath-Mistral-7B
  expert_2:
    _target_: transformers.AutoModelForCausalLM.from_pretrained
    pretrained_model_name_or_path: cognitivecomputations/dolphin-2.1-mistral-7b
  expert_3:
    _target_: transformers.AutoModelForCausalLM.from_pretrained
    pretrained_model_name_or_path: uukuguy/speechless-code-mistral-7b-v1.0
model_kwargs:
  torch_dtype: float16
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: mistralai/Mistral-7B-v0.1
