defaults:
  - /dataset/image_classification/train@train_datasets:
      - stanford-cars
      - dtd
  - /dataset/image_classification/test@test_datasets:
      - stanford-cars
      - dtd
_target_: fusion_bench.modelpool.OpenCLIPVisionModelPool
_recursive_: false
model_dir: ./.cache/task_vectors_checkpoints/
models:
  _pretrained_:
    model_name: ViT-B-32
    pickle_path: ${...model_dir}/ViT-B-32/zeroshot.pt
  stanford-cars:
    model_name: ViT-B-32
    pickle_path: ${...model_dir}/ViT-B-32/Cars/finetuned.pt
  dtd:
    model_name: ViT-B-32
    pickle_path: ${...model_dir}/ViT-B-32/DTD/finetuned.pt
classification_heads:
  stanford-cars: ${..model_dir}/ViT-B-32/head_Cars.pt
  dtd: ${..model_dir}/ViT-B-32/head_DTD.pt
