defaults:
  - /dataset/image_classification/train@train_datasets:
      - sun397
      - stanford-cars
  - /dataset/image_classification/test@test_datasets:
      - sun397
      - stanford-cars
_target_: fusion_bench.modelpool.OpenCLIPVisionModelPool
_recursive_: false
model_dir: ./.cache/task_vectors_checkpoints/
models:
  _pretrained_:
    model_name: ViT-B-32
    pickle_path: ${...model_dir}/ViT-B-32/zeroshot.pt
  sun397:
    model_name: ViT-B-32
    pickle_path: ${...model_dir}/ViT-B-32/SUN397/finetuned.pt
  stanford-cars:
    model_name: ViT-B-32
    pickle_path: ${...model_dir}/ViT-B-32/Cars/finetuned.pt
classification_heads:
  sun397: ${..model_dir}/ViT-B-32/head_SUN397.pt
  stanford-cars: ${..model_dir}/ViT-B-32/head_Cars.pt
