_target_: fusion_bench.method.singular_value_calibration.generic.SingularValueCalibrationWithBaseMethod
alpha: 0.2
accelerator: null
base_method:
  _target_: fusion_bench.method.ISO_CTS_Merge
  scaling_factor: 1.5
  common_space_fraction: 0.8
  exclude_keys: null
