_target_: fusion_bench.modelpool.Seq2SeqLMPool
_recursive_: false
_version_: "0.2"
models: ???
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: google/flan-t5-base
model_kwargs: null
