_pretrained_:
  _target_: transformers.CLIPVisionModel.from_pretrained
#  pretrained_model_name_or_path: openai/clip-vit-base-patch32
  pretrained_model_name_or_path: /home/htl/.cache/huggingface/hub/models--openai--clip-vit-base-patch32/snapshots/3d74acf9a28c67741b2f4f2ea7635f0aaf6f0268
