stanford-cars:
  _target_: transformers.CLIPVisionModel.from_pretrained
#  pretrained_model_name_or_path: tanganke/clip-vit-base-patch32_stanford-cars
  pretrained_model_name_or_path: /home/htl/.cache/huggingface/hub/models--tanganke--clip-vit-base-patch32_stanford-cars/snapshots/0fa3456c60f15e5cec5275c5b88851c1dca503a8
