gtsrb:
  _target_: transformers.CLIPVisionModel.from_pretrained
#  pretrained_model_name_or_path: tanganke/clip-vit-base-patch32_gtsrb
  pretrained_model_name_or_path: /home/htl/.cache/huggingface/hub/models--tanganke--clip-vit-base-patch32_gtsrb/snapshots/7b11ced426cc9cd0430650be19d75748f3bd64d0
