dtd:
  _target_: transformers.CLIPVisionModel.from_pretrained
#  pretrained_model_name_or_path: tanganke/clip-vit-base-patch32_dtd
  pretrained_model_name_or_path:   /home/htl/.cache/huggingface/hub/models--tanganke--clip-vit-base-patch32_dtd/snapshots/2ce76d4ca9ae563f45f526d4f2d222478083784c
