_target_: lightning.fabric.strategies.FSDPStrategy
sharding_strategy: FULL_SHARD
cpu_offload: false
auto_wrap_policy:
  _target_: fusion_bench.mixins.lightning_fabric.get_policy
  _args_:
    - transformers.models.llama.modeling_llama.LlamaDecoderLayer
activation_checkpointing_policy: ${.auto_wrap_policy}
