# Generic SMILE Upscaling Configuration for CausalLM models
# Supports: Qwen2, Llama, Mistral models
# The model type will be auto-detected from the base model
_target_: fusion_bench.method.smile_upscaling.causal_lm_upscaling.SmileCausalLMUpscalingAlgorithm

# Device and computation settings
device: cuda # device to put the models on
accelerator: cuda # device to perform SVD on

# Model upscaling parameters
num_experts_per_tok: 1 # Number of experts to activate per token
rank_of_router: 8 # Rank for router weights
rank_of_expert: 64 # Rank for expert weights

# Model saving settings
model_save_path: ${path.log_dir}/checkpoint # Set to save the merged model
model_dtype: null # Optional: convert to specific dtype after merging
save_with_remote_code: true

# Optional: Explicitly specify model type instead of auto-detection
model_type: null # Options: "qwen2", "llama", "mistral", or null for auto-detection
