_target_: fusion_bench.modelpool.CLIPVisionModelPool
_recursive_: False

models:
  _pretrained_: openai/clip-vit-base-patch32
  gtsrb: ./outputs/logs/ViT-B-32/continual_clip_layer_wise_adamerging_adamerging/5/version_0/merged_model
  mnist: tanganke/clip-vit-base-patch32_mnist

test_datasets:
  gtsrb:
    _target_: datasets.load_dataset
    path: tanganke/gtsrb
    split: test
  mnist:
    _target_: datasets.load_dataset
    path: mnist
    split: test

processor:
  _target_: transformers.CLIPProcessor.from_pretrained
  pretrained_model_name_or_path: openai/clip-vit-base-patch32
