_target_: fusion_bench.modelpool.CLIPVisionModelPool
_recursive_: False

models:
  _pretrained_: openai/clip-vit-base-patch32
  mnist: ./outputs/logs/ViT-B-32/continual_clip_layer_wise_adamerging_adamerging/6/version_0/merged_model
  dtd: tanganke/clip-vit-base-patch32_dtd

test_datasets:
  mnist:
    _target_: datasets.load_dataset
    path: mnist
    split: test
  dtd:
    _target_: datasets.load_dataset
    path: tanganke/dtd
    split: test

processor:
  _target_: transformers.CLIPProcessor.from_pretrained
  pretrained_model_name_or_path: openai/clip-vit-base-patch32
