type: huggingface_clip_vision
models:
  - name: _pretrained_
    path: openai/clip-vit-base-patch32
  - name: sun397
    path: tanganke/clip-vit-base-patch32_sun397
  - name: stanford_cars
    path: tanganke/clip-vit-base-patch32_stanford-cars
  - name: resisc45
    path: tanganke/clip-vit-base-patch32_resisc45
  - name: svhn
    path: tanganke/clip-vit-base-patch32_svhn
  - name: gtsrb
    path: tanganke/clip-vit-base-patch32_gtsrb
  - name: dtd
    path: tanganke/clip-vit-base-patch32_dtd

# The following datasets are used for test-time adaptation
dataset_type: huggingface_image_classification
tta_datasets:
  - name: svhn
    dataset:
      type: instantiate
      name: svhn
      object:
        _target_: datasets.load_dataset
        _args_:
          - svhn
          - cropped_digits
        split: test
  - name: stanford_cars
    dataset:
      name: tanganke/stanford_cars
      split: test
  - name: resisc45
    dataset:
      name: tanganke/resisc45
      split: test
  - name: gtsrb
    dataset:
      name: tanganke/gtsrb
      split: test
  - name: dtd
    dataset:
      name: tanganke/dtd
      split: test
  - name: sun397
    dataset:
      name: tanganke/sun397
      split: test

# the following datasets are used for Fisher Merging, RegMean
train_datasets:
  - name: svhn
    dataset:
      type: instantiate
      name: svhn
      object:
        _target_: datasets.load_dataset
        _args_:
          - svhn
          - cropped_digits
        split: train
  - name: stanford_cars
    dataset:
      name: tanganke/stanford_cars
      split: train
  - name: resisc45
    dataset:
      name: tanganke/resisc45
      split: train
  - name: gtsrb
    dataset:
      name: tanganke/gtsrb
      split: train
  - name: dtd
    dataset:
      name: tanganke/dtd
      split: train
  - name: sun397
    dataset:
      name: tanganke/sun397
      split: train
