type: huggingface_clip_vision
models:
  - name: _pretrained_
    path: openai/clip-vit-base-patch32
  - name: sun397
    path: tanganke/clip-vit-base-patch32_sun397
  - name: stanford_cars
    path: tanganke/clip-vit-base-patch32_stanford-cars
  - name: eurosat
    path: tanganke/clip-vit-base-patch32_eurosat
  - name: gtsrb
    path: tanganke/clip-vit-base-patch32_gtsrb
  - name: mnist
    path: tanganke/clip-vit-base-patch32_mnist
  - name: dtd
    path: tanganke/clip-vit-base-patch32_dtd


# The following datasets are used for test-time adaptation
dataset_type: huggingface_image_classification
tta_datasets:
  - name: stanford_cars
    dataset:
      name: tanganke/stanford_cars
      split: test
  - name: eurosat
    dataset:
      name: tanganke/eurosat
      split: test
  - name: gtsrb
    dataset:
      name: tanganke/gtsrb
      split: test
  - name: mnist
    dataset:
      name: mnist
      split: test
  - name: dtd
    dataset:
      name: tanganke/dtd
      split: test
  - name: sun397
    dataset:
      name: tanganke/sun397
      split: test

train_datasets:
  - name: stanford_cars
    dataset:
      name: tanganke/stanford_cars
      split: train
  - name: eurosat
    dataset:
      name: tanganke/eurosat
      split: train
  - name: gtsrb
    dataset:
      name: tanganke/gtsrb
      split: train
  - name: mnist
    dataset:
      name: mnist
      split: train
  - name: dtd
    dataset:
      name: tanganke/dtd
      split: train
  - name: sun397
    dataset:
      name: tanganke/sun397
      split: train
