type: huggingface_clip_vision
models:
  - name: _pretrained_
    path: openai/clip-vit-base-patch32

dataset_type: huggingface_image_classification
train_datasets:
  - name: svhn
    dataset:
      type: instantiate
      name: svhn
      object:
        _target_: datasets.load_dataset
        _args_:
          - svhn
          - cropped_digits
        split: train
  - name: stanford_cars
    dataset:
      name: tanganke/stanford_cars
      split: train
  - name: resisc45
    dataset:
      name: tanganke/resisc45
      split: train
  - name: eurosat
    dataset:
      name: tanganke/eurosat
      split: train
  - name: gtsrb
    dataset:
      name: tanganke/gtsrb
      split: train
  - name: mnist
    dataset:
      name: mnist
      split: train
  - name: dtd
    dataset:
      name: tanganke/dtd
      split: train
  - name: sun397
    dataset:
      name: tanganke/sun397
      split: train
