type: clip_vit_classification
name: clip-vit-classification_TA8

dataset_type: huggingface_image_classification
tasks:
  - name: svhn
    dataset:
      type: instantiate
      name: svhn
      object: 
        _target_: datasets.load_dataset
        _args_:
          - svhn
          - cropped_digits
        split: test
  - name: stanford_cars
    dataset:
      name: tanganke/stanford_cars
      split: test
  - name: resisc45
    dataset:
      name: tanganke/resisc45
      split: test
  - name: eurosat
    dataset:
      name: tanganke/eurosat
      split: test
  - name: gtsrb
    dataset:
      name: tanganke/gtsrb
      split: test
  - name: mnist
    dataset:
      name: mnist
      split: test
  - name: dtd
    dataset:
      name: tanganke/dtd
      split: test
  - name: sun397
    dataset:
      name: tanganke/sun397
      split: test

clip_model: openai/clip-vit-large-patch14
batch_size: 64
num_workers: 16
fast_dev_run: ${fast_dev_run}
