defaults:
  - clip-vit-large-patch14
  - clip-vit-large-patch14_sun397
  - clip-vit-large-patch14_stanford-cars
  - clip-vit-large-patch14_resisc45
  - clip-vit-large-patch14_eurosat
  - clip-vit-large-patch14_svhn
  - clip-vit-large-patch14_gtsrb
  - clip-vit-large-patch14_mnist
  - clip-vit-large-patch14_dtd
