# The 20 task used in the paper: 
# Wang et al. Localizing Task Information for Improved Model Merging and Compression
# http://arxiv.org/abs/2405.07813
defaults:
  # pre-trained model
  - clip-vit-base-patch16
  # eight tasks in the task arithmetic paper
  - clip-vit-base-patch16_sun397
  - clip-vit-base-patch16_stanford-cars
  - clip-vit-base-patch16_resisc45
  - clip-vit-base-patch16_eurosat
  - clip-vit-base-patch16_svhn
  - clip-vit-base-patch16_gtsrb
  - clip-vit-base-patch16_mnist
  - clip-vit-base-patch16_dtd
  # additional 6 tasks in the TALL mask paper (TALL 14)
  - clip-vit-base-patch16_oxford_flowers102
  - clip-vit-base-patch16_pcam
  - clip-vit-base-patch16_fer2013
  - clip-vit-base-patch16_oxford-iiit-pet
  - clip-vit-base-patch16_stl10
  - clip-vit-base-patch16_cifar100
  # additional 6 tasks in the TALL mask paper (TALL 20)
  - clip-vit-base-patch16_cifar10
  - clip-vit-base-patch16_food101
  - clip-vit-base-patch16_fashion_mnist
  - clip-vit-base-patch16_emnist_letters
  - clip-vit-base-patch16_kmnist
  - clip-vit-base-patch16_rendered-sst2
