defaults:
  - hydra: default
  - fabric: auto
  # --- Model, Method, Task ---
  - modelpool: CLIPVisionModelPool/clip-vit-base-patch32_generalization_exp2
  # - modelpool: test/clip-adamerging-3model
  - method: adamerging
  - taskpool: CLIPVisionModelTaskPool/clip-vit-classification_TA8
  # - taskpool: test/clip-adamerging-3model
  - _self_

_target_: fusion_bench.programs.FabricModelFusionProgram
_recursive_: false
fast_dev_run: false # Run a single batch of data to test the model or method
# Run the script without actually running the experiment, use with `print_config=true`. 
# You can also use `--cfg` or `-c` to  show the configuration instead of runing.
dry_run: false
print_config: true # Print the configuration to the console
merged_model_save_path: null # path to save the merged model, use "{log_dir}" to refer to the logger directory, for example `merged_model_save_path=\{log_dir\}/merged_model`
merged_model_save_kwargs: null
# report_save_path: outputs/clip-vit-base-patch32_generalization_exp1_clip_layer_wise_adamerging.json # path to save the result report
print_function_call: true # set to false if you don't want to print the details of instantiate calls

# method.save_merging_weights: outputs/clip-vit-base-patch32_generalization_exp1_layer_wise_adamerging_weights.pt