defaults:
  - hydra: default
  - fabric: auto
  - modelpool: nyuv2_modelpool
  - method: simple_average
  - taskpool: nyuv2_taskpool
  - _self_
_target_: fusion_bench.programs.FabricModelFusionProgram
_recursive_: false
fast_dev_run: false # Run a single batch of data to test the model or method
use_lightning: true # Use the fabric to run the experiment
print_config: true # Print the configuration to the console
save_report: false # path to save the result report
trainer:
  devices: 1
