defaults:
  - /dataset/image_classification/train@train_datasets:
      - sun397
      - stanford-cars
      - resisc45
      - eurosat
      - svhn
      - gtsrb
      - mnist
      - dtd
  - /dataset/image_classification/test@test_datasets:
      - sun397
      - stanford-cars
      - resisc45
      - eurosat
      - svhn
      - gtsrb
      - mnist
      - dtd
_target_: fusion_bench.modelpool.CLIPVisionModelPool
_recursive_: False
processor: openai/clip-vit-large-patch14
models:
  _pretrained_: openai/clip-vit-large-patch14
  sun397: tanganke/clip-vit-large-patch14_sun397
  stanford-cars: tanganke/clip-vit-large-patch14_stanford-cars
  resisc45: tanganke/clip-vit-large-patch14_resisc45
  eurosat: tanganke/clip-vit-large-patch14_eurosat
  svhn: tanganke/clip-vit-large-patch14_svhn
  gtsrb: tanganke/clip-vit-large-patch14_gtsrb
  mnist: tanganke/clip-vit-large-patch14_mnist
  dtd: tanganke/clip-vit-large-patch14_dtd
platform: hf
