defaults:
  - /dataset/image_classification/train@train_datasets:
      - sun397
      - stanford-cars
  - /dataset/image_classification/test@test_datasets:
      - sun397
      - stanford-cars
_target_: fusion_bench.modelpool.CLIPVisionModelPool
_recursive_: False
processor: openai/clip-vit-base-patch32
models:
  _pretrained_: openai/clip-vit-base-patch32
  sun397: tanganke/clip-vit-base-patch32_sun397
  stanford-cars: tanganke/clip-vit-base-patch32_stanford-cars
platform: hf
