_target_: fusion_bench.modelpool.CLIPVisionModelPool

models:
  sun397:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_sun397_lora-16

processor:
  _target_: transformers.CLIPProcessor.from_pretrained
  pretrained_model_name_or_path: openai/clip-vit-base-patch16

train_datasets: null
test_datasets: null
