_target_: fusion_bench.modelpool.CLIPVisionModelPool
_recursive_: False
processor: openai/clip-vit-base-patch32
models:
  _pretrained_: openai/clip-vit-base-patch32
  svhn: tanganke/clip-vit-base-patch32_svhn
  mnist: tanganke/clip-vit-base-patch32_mnist
platform: hf
