# eight image classification tasks defined in task arithmetic paper
defaults:
  - /dataset/image_classification/train@train_datasets:
      - sun397
      - stanford-cars
      - resisc45
      - eurosat
      - svhn
      - gtsrb
      - mnist
      - dtd
  - /dataset/image_classification/test@test_datasets:
      - sun397
      - stanford-cars
      - resisc45
      - eurosat
      - svhn
      - gtsrb
      - mnist
      - dtd
  - _self_
_target_: fusion_bench.modelpool.CLIPVisionModelPool
_recursive_: False
processor: openai/clip-vit-base-patch32
models:
  _pretrained_: openai/clip-vit-base-patch32
  sun397: tanganke/clip-vit-base-patch32_sun397
  stanford-cars: tanganke/clip-vit-base-patch32_stanford-cars
  resisc45: tanganke/clip-vit-base-patch32_resisc45
  eurosat: tanganke/clip-vit-base-patch32_eurosat
  svhn: tanganke/clip-vit-base-patch32_svhn
  gtsrb: tanganke/clip-vit-base-patch32_gtsrb
  mnist: tanganke/clip-vit-base-patch32_mnist
  dtd: tanganke/clip-vit-base-patch32_dtd
platform: hf
