# The 20 task used in the paper: 
# Wang et al. Localizing Task Information for Improved Model Merging and Compression
# http://arxiv.org/abs/2405.07813
_target_: fusion_bench.modelpool.CLIPVisionModelPool
_recursive_: False
processor: openai/clip-vit-base-patch32
models:
  _pretrained_: openai/clip-vit-base-patch32
  sun397: tanganke/clip-vit-base-patch32_sun397
  stanford-cars: tanganke/clip-vit-base-patch32_stanford-cars
  resisc45: tanganke/clip-vit-base-patch32_resisc45
  eurosat: tanganke/clip-vit-base-patch32_eurosat
  svhn: tanganke/clip-vit-base-patch32_svhn
  gtsrb: tanganke/clip-vit-base-patch32_gtsrb
  mnist: tanganke/clip-vit-base-patch32_mnist
  dtd: tanganke/clip-vit-base-patch32_dtd
  oxford_flowers102: tanganke/clip-vit-base-patch32_oxford_flowers102
  pcam: tanganke/clip-vit-base-patch32_pcam
  fer2013: tanganke/clip-vit-base-patch32_fer2013
  oxford-iiit-pet: tanganke/clip-vit-base-patch32_oxford-iiit-pet
  stl10: tanganke/clip-vit-base-patch32_stl10
  cifar100: tanganke/clip-vit-base-patch32_cifar100
  cifar10: tanganke/clip-vit-base-patch32_cifar10
  food101: tanganke/clip-vit-base-patch32_food101
  fashion_mnist: tanganke/clip-vit-base-patch32_fashion_mnist
  emnist_letters: tanganke/clip-vit-base-patch32_emnist_letters
  kmnist: tanganke/clip-vit-base-patch32_kmnist
  rendered-sst2: tanganke/clip-vit-base-patch32_rendered-sst2
platform: hf
