defaults:
  - /dataset/image_classification/train@train_datasets:
      - sun397
      - dtd
  - /dataset/image_classification/test@test_datasets:
      - sun397
      - dtd
_target_: fusion_bench.modelpool.CLIPVisionModelPool
_recursive_: False
processor: openai/clip-vit-base-patch32
models:
  _pretrained_: openai/clip-vit-base-patch32
  sun397: tanganke/clip-vit-base-patch32_sun397
  dtd: tanganke/clip-vit-base-patch32_dtd
platform: hf
