_target_: fusion_bench.method.TiesMergingAlgorithm
# Scaling factor $\lambda$
scaling_factor: 0.3
threshold: 20
# List of keys to remove from the state dict, default is empty
remove_keys: []
# Function to merge the models, default is sum. Options are 'sum', 'mean', and 'max'
merge_func: sum
