_target_: fusion_bench.method.linear.llama_expo.ExPOWithDareForLLama
extrapolation_factor: 0.1
attention_scaling_factor: 1.0
only_on_backbone: true
on_linear_weights: true
on_linear_bias: false
on_embedding: false
fix_last_n_layers: 0
fix_first_n_layers: 0
magnitude_sparsity_ratio: null
# dare arguments
dare_sparsity_ratio: 0.5
dare_only_on_linear_weights: true
dare_rescale: true
