type: AutoModelForCausalLMPool
# each model should have a name and a path, and the model is loaded from the path
# this is equivalent to `AutoModelForCausalLM.from_pretrained(path)`
models:
  - name: _pretrained_
    path: mistralai/Mistral-7B-v0.1
  - name: expert_1
    path: meta-math/MetaMath-Mistral-7B
  - name: expert_2
    path: cognitivecomputations/dolphin-2.1-mistral-7b
  - name: expert_3
    path: uukuguy/speechless-code-mistral-7b-v1.0
dtype: float16
