_target_: lightning.fabric.strategies.FSDPStrategy
sharding_strategy: FULL_SHARD
state_dict_type: full # Save a single, consolidated checkpoint file
cpu_offload: false
auto_wrap_policy:
  _target_: fusion_bench.mixins.lightning_fabric.get_size_based_auto_wrap_policy
activation_checkpointing_policy: ${.auto_wrap_policy}
# limit_all_gathers: true
