_target_: fusion_bench.method.classification.ImageClassificationFineTuning
max_epochs: 10
max_steps: null
label_smoothing: 0
optimizer:
  _target_: torch.optim.SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 1e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${..max_epochs}
dataloader_kwargs:
  batch_size: 256 # batch size per GPU
  num_workers: 8
  pin_memory: true
