_target_: fusion_bench.method.s2_moe.s2_moe_llama_upscaling.S2MoEUpscalingAlgorithmForLlama
# the device where we put the models on, merge device on cuda can accelerate the SVD computation
device: cpu
# the device to compute svd
upscaling_accelerator: cuda
full_matrices: true # set to false if you are sure k < rank
top_k: 1
routing_use_diff: true
# average the remaining part, if this is set the False, the remaining part will kept as base model (the pretrained model)
average_experts: false
# path to save/load the model
model_path: null
model_save_path: ./save_models/llama3.2-3B_S2MoE
threshold: 0.1
use_aparse_expert: true
sparsity_ratio: 0.80

