dtd:
  _target_: fusion_bench.utils.data.train_validation_split
  dataset:
    _target_: datasets.load_dataset
    path: tanganke/dtd
    split: train
  validation_fraction: 0.1
  validation_size: null
  random_seed: 0
  return_split: val
