_target_: fusion_bench.method.SimpleAverageForLlama
# set `merge_backbone` to true if you has a base model and only want to merge the backbone of the experts
# if `merge_backbone` is False, this is equivalent to `SimpleAverageAlgorithm`
merge_backbone: true
model_save_path: null
